[global]
username = janders223
use_keyring = true
use_mpris = true
backend = portaudio
volume_controller = softvol
device_name = nixer
bitrate = 320
no_audio_cache = true
initial_volume = 90
volume_normalisation = true
normalisation_pregain = -10
zeroconf_port = 1234
proxy = http://localhost:3128
device_type = computer
