name: "Check Nix Flake"
on:
  pull_request:
  push:
    branches:
      - main
      - nix

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@6004951b182f8860210c8d6f0d808ec5b1a33d28 # v25
      - name: Check flake
        run: nix --extra-experimental-features 'nix-command flakes' flake check --all-systems
